site_name: Specular Differentiation
site_url: https://kyjung2357.github.io/specular-differentiation
repo_url: https://github.com/kyjung2357/specular-differentiation
edit_uri: edit/main/docs/

theme:
  name: material
  logo: figures/specular-differentiation-logo.png
  favicon: figures/specular-differentiation-logo.png
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: custom
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.footer

plugins:
  - search
  - callouts
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            heading_level: 3
            line_length: 88
            members_order: source
            separate_signature: true
            show_source: true
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_object_full_path: false
            show_root_members_full_path: false
  - include-markdown:
      rewrite_relative_urls: true

hooks:
  - docs/hooks/code_copy_buttons.py
  

nav:
  - Home: index.md
  - Quick start: quick-start.md
  - Examples:
    - Scalar ODE examples: examples/ode/index.md
  - LaTeX Macro: started/latex-macro.md
  - API Reference:
    - Calculation: api/calculation.md
    - ODE: api/ode.md
    - Backends: api/backend.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/header-home-link.js
  - javascripts/code-copy-buttons.js
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
