site_name: Specular Differentiation
site_url: https://kyjung2357.github.io/specular-differentiation
repo_url: https://github.com/kyjung2357/specular-differentiation
edit_uri: edit/main/docs/

theme:
  name: material
  logo: figures/specular-differentiation-logo.png
  favicon: figures/specular-differentiation-logo.png
  palette:
    - scheme: default
      primary: custom
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.footer
    - toc.integrate

plugins:
  - search
  - callouts
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 1
  - include-markdown:
      rewrite_relative_urls: true
  

nav:
  - Home: index.md
  - 1. Getting Started:
    - overview: started/index.md
    - 1.1. User installation: started/installation.md
    - 1.2. Quick start: started/quick-start.md
    - 1.3. Backend Usage: started/backend-usage.md
  - 2. API Reference:
    - overview: api/index.md
    - 2.1. Calculation: api/calculation.md
    - 2.2. ODE: api/ode.md
    - 2.3. Optimization: api/optimization.md
    - 2.4. Backend: api/backend.md
  - 3. Examples:
    - overview: examples/index.md
    - 3.1. Ordinary differential equation:
      - overview: examples/ode.md
      - 2026-Jung: examples/ode-2026-jung.md
    - 3.2. Optimization:
      - overview: examples/optimization.md
      - 2026-Jung: examples/optimization-2026-jung.md
      - 2024-Jung-Oh: examples/optimization-2024-jung-oh.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/header-home-link.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
