[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "specular-differentiation"
version = "1.3.0"
description = "Specular differentiation in normed vector spaces and its applications"
requires-python = ">=3.14"
license = "MIT"
authors = [{name = "Kiyuob Jung", email = "kyjung@msu.edu"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics"
]
dependencies = [
    "numpy>=2.4"
]

readme = "README.md"

[project.urls]
"Documentation" = "https://kyjung2357.github.io/specular-differentiation"
"Repository" = "https://github.com/kyjung2357/specular-differentiation"
"Issues" = "https://github.com/kyjung2357/specular-differentiation/issues"

[project.optional-dependencies]
jax = [
    "jax>=0.10",
    "jaxlib>=0.10"
]

numba = [
    "numba>=0.65"
]

dev = [
    "specular-differentiation[numba]",
    "specular-differentiation[jax]",
    "pytest>=9.0",
    "scipy>=1.17",
    "ipython>=9.13",
    "matplotlib>=3.10",
]

docs = [
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-callouts",
    "mkdocs-include-markdown-plugin",
]

[tool.setuptools.packages.find]
include = ["specular*"]
exclude = ["unpublished*", "tests*", "docs*", "examples*"]
