[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "specular-differentiation"
version = "1.2.1"
description = "Specular differentiation in normed vector spaces and its applications"
requires-python = ">=3.11"
license = {text = "MIT License"}
authors = [{name = "Kiyuob Jung", email = "kyjung@msu.edu"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics"
]
dependencies = [
    "numpy>=2.0"
]

readme = "README.md"

[project.urls]
"Homepage" = "https://github.com/kyjung2357/specular-differentiation"
"Bug Tracker" = "https://github.com/kyjung2357/specular-differentiation/issues"

[project.optional-dependencies]
jax = [
    "jax>=0.4",
    "jaxlib>=0.4"
]

numba = [
    "numba>=0.57"
]

ode = [
    "matplotlib",
    "pandas",
    "tqdm"
]

optimization = [
    "matplotlib",
    "tqdm",
]

dev = [
    "specular-differentiation[ode]",
    "specular-differentiation[optimization]",
    "specular-differentiation[numba]",
    "specular-differentiation[jax]",
    "pytest>=7.0",
    "scipy>=1.10.0",
    "torch>=2.0.0",
    "ipython",
]

[tool.setuptools.packages.find]
include = ["specular*"]
exclude = ["unpublished*", "tests*", "docs*", "examples*"]