[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "specular-differentiation"
version = "1.3.0"
description = "Specular differentiation in normed vector spaces and its applications"
requires-python = ">=3.14"
license = {text = "MIT License"}
authors = [{name = "Kiyuob Jung", email = "kyjung@msu.edu"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics"
]
dependencies = [
    "numpy>=2.4"
]

readme = "README.md"

[project.urls]
"Documentation" = "https://kyjung2357.github.io/specular-differentiation"
"Repository" = "https://github.com/kyjung2357/specular-differentiation"
"Issues" = "https://github.com/kyjung2357/specular-differentiation/issues"

[project.optional-dependencies]
jax = [
    "jax>=0.10",
    "jaxlib>=0.10"
]

numba = [
    "numba>=0.65"
]

torch = [
    "torch>=2.12"
]

ode = [
    "matplotlib>=3.10",
    "pandas>=3.0",
    "tqdm>=4.67"
]

optimization = [
    "matplotlib>=3.10",
    "tqdm>=4.67",
]

dev = [
    "specular-differentiation[ode]",
    "specular-differentiation[optimization]",
    "specular-differentiation[numba]",
    "specular-differentiation[jax]",
    "pytest>=9.0",
    "scipy>=1.17",
    "torch>=2.12",
    "ipython>=9.13",
]

docs = [
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-callouts",
    "mkdocs-include-markdown-plugin",
]

[tool.setuptools.packages.find]
include = ["specular*"]
exclude = ["unpublished*", "tests*", "docs*", "examples*"]